name: 'Unit Tests with Coverage'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test --coverage

      - name: Display Node.js version
        run: node -v

      - name: Display npm version
        run: npm -v

      - name: Debug environment variables
        run: printenv
